(deftheme vibrant-ink
  "Emacs 24 theme based on Vibrant Ink for Textmate")

(custom-theme-set-faces
 'vibrant-ink
 '(bold ((t (:bold t))))
 '(bold-italic ((t (:bold t))))
 '(button ((t (:background "#bfbfbf" :underline t))))
 '(cursor ((t (:background "#ffffff" :foreground "#000000"))))
 '(default ((t (:background "#111111" :foreground "#ffffff"))))
 '(erb-delim-face ((t (:foreground "#E6E1DC" ))))
 '(erb-exec-face ((t (:background "#191919"))))
 '(erb-out-delim-face ((t (:foreground "#E6E1DC"))))
 '(erb-out-face ((t (:background "#191919"))))
 '(eshell-prompt ((t (:foreground "#ff6600"))))
 '(flymake-errline ((t (:background "#cc2200" :foreground "white"))))
 '(flymake-warnline ((t (:background "LightSteelBlue" :foreground "black"))))
 '(font-lock-builtin-face ((t (:foreground "#aaccff"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#9933cc"))))
 '(font-lock-comment-face ((t (:slant italic :foreground "#9933cc"))))
 '(font-lock-constant-face ((t (:foreground "#339999"))))
 '(font-lock-doc-face ((t (:foreground "LightSalmon"))))
 '(font-lock-function-name-face ((t (:foreground "#ffcc00"))))
 '(font-lock-keyword-face ((t (:foreground "#ff6600"))))
 '(font-lock-preprocessor-face ((t (:foreground "#aaffff"))))
 '(font-lock-reference-face ((t (:foreground "LightSteelBlue"))))
 '(font-lock-string-face ((t (:foreground "#66ff00"))))
 '(font-lock-type-face ((t (:foreground "#aaaaaa"))))
 '(font-lock-variable-name-face ((t (:foreground "#aaccff"))))
 '(font-lock-warning-face ((t (:foreground "#ffb5d0" :weight bold))))
 '(fringe ((t (:background "#000000"))))
 '(header-line ((t (:background "#e5e5e5" :foreground "#333333"))))
 '(highlight ((t (:background "#333333"))))
 '(isearch ((t (:background "#ffcc00" :foreground "#000000"))))
 '(lazy-highlight ((t (:background "#9933cc" :foreground "white"))))
 '(link ((t (:foreground "#aaccff" :underline t))))
 '(link-visited ((t (:foreground "#aaccff" :underline t))))
 '(minibuffer-prompt ((t (:foreground "#ff6600"))))
 '(mode-line ((t (:background "#e5e5e5" :foreground "#000000"))))
 '(mode-line-buffer-id ((t (:background "#a5baf1" :foreground "black"))))
 '(mode-line-inactive ((t (:background "#909090" :foreground "#333333"))))
 '(paren-face-match-light ((t (:background "#222222"))))
 '(primary-selection ((t (:background "#555577"))))
 '(region ((t (:background "#881199"))))
 '(enh-ruby-op-face ((t (:foreground "PeachPuff3"))))
 '(secondary-selection ((t (:background "darkslateblue"))))
 '(underline ((t (:underline t))))
 '(zmacs-region ((t (:background "#555577")))))

(provide-theme 'vibrant-ink)
